parameters:
  default.host: host.docker.internal # localhost for Mac
  default.port: 8080
  login: 'test'
  password: 'password'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  default.request.factory:
    class: Xpat\ApiTest\Request\DefaultRequestFactory
    arguments: [ '%default.host%', '%default.port%' ]
    autowire: true

  ApiTest\:
    resource: '../tests/*'
    arguments: [ '@default.request.factory' ]

  App\AuthenticatedRequestFactory:
    class: App\AuthenticatedRequestFactory
    arguments: [ '@erp.request.factory', '%login%', '%password%' ]

  ApiTest\Private\:
    resource: '../tests/Private/*'
    arguments: [ '@App\AuthenticatedRequestFactory' ]